<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>mifss-commons</artifactId>
        <groupId>com.aeye.mifss</groupId>
        <version>v2026.01</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>mifss-commons-web</artifactId>
    <description>通用Web层配置</description>

    <dependencies>

        <dependency>
            <groupId>com.aeye.mifss</groupId>
            <artifactId>mifss-commons-util</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.hsa.hsaf.core</groupId>
            <artifactId>hsaf-core</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.hsa.hsaf.core</groupId>
            <artifactId>hsaf-idgenerator</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.hsa.hsaf.adapt</groupId>
            <artifactId>hsaf-cache-redis</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.security.oauth.boot</groupId>
            <artifactId>spring-security-oauth2-autoconfigure</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcprov-jdk15on</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- security 版本升级jdk15on到1.7 -->
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>1.70</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>cn.hsa.hsaf.auth.security</groupId>
            <artifactId>hsaf-auth-security</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-redis</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.xuxueli</groupId>
            <artifactId>xxl-job-core</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
        </dependency>

        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
        </dependency>

        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-spring-ui</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.aeye.mifss</groupId>
            <artifactId>mifss-commons-orm</artifactId>
        </dependency>

    </dependencies>

</project>
