<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>mifss-adapters</artifactId>
        <groupId>com.aeye.mifss</groupId>
        <version>v2026.01</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>mifss-adapter-huawei</artifactId>
    <description>华为云适配</description>

    <dependencies>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.hsa.hsaf.core</groupId>
            <artifactId>hsaf-core</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.hsa.hsaf.core</groupId>
            <artifactId>hsaf-idgenerator</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.hsa.hsaf.adapt</groupId>
            <artifactId>hsaf-cache-redis</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.hsa.hsaf.auth.security</groupId>
            <artifactId>hsaf-auth-security</artifactId>
        </dependency>

        <!--华为springCloud适配-->
        <dependency>
            <groupId>com.huaweicloud</groupId>
            <artifactId>spring-cloud-starter-huawei-servicecomb-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>com.huaweicloud</groupId>
            <artifactId>spring-cloud-starter-huawei-config</artifactId>
        </dependency>
        <dependency>
            <groupId>com.huaweicloud</groupId>
            <artifactId>spring-cloud-starter-huawei-governance</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.hsa.hsaf.adapt</groupId>
            <artifactId>hsaf-huawei-springcloud-rpc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>

        <!--redis缓存-->
        <dependency>
            <groupId>cn.hsa.hsaf.adapt</groupId>
            <artifactId>hsaf-huawei-cache</artifactId>
        </dependency>

        <!--文件存储-->
        <dependency>
            <groupId>cn.hsa.hsaf.adapt</groupId>
            <artifactId>hsaf-huawei-fsstore</artifactId>
        </dependency>
        <dependency>
            <groupId>com.huawei.storage</groupId>
            <artifactId>esdk-obs-java</artifactId>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
        </dependency>

        <!--消息队列-->
        <dependency>
            <groupId>cn.hsa.hsaf.adapt</groupId>
            <artifactId>hsaf-huawei-mq</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
        </dependency>

        <!--网关-->
        <dependency>
            <groupId>cn.hsa.hsaf.adapt</groupId>
            <artifactId>hsaf-huawei-gateway</artifactId>
        </dependency>

    </dependencies>

</project>